/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BookRouteImport } from './routes/book'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as AppWaitlistRouteImport } from './routes/app.waitlist'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppPublicProfileRouteImport } from './routes/app.public-profile'
import { Route as AppOperatorsRouteImport } from './routes/app.operators'
import { Route as AppMenuRouteImport } from './routes/app.menu'
import { Route as AppFloorPlanRouteImport } from './routes/app.floor-plan'
import { Route as AppCustomersRouteImport } from './routes/app.customers'
import { Route as AppCashierRouteImport } from './routes/app.cashier'
import { Route as AppBookingsRouteImport } from './routes/app.bookings'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as ApiPublicHooksWhatsappWebhookRouteImport } from './routes/api/public/hooks/whatsapp-webhook'
import { Route as ApiPublicHooksWhatsappDispatchRouteImport } from './routes/api/public/hooks/whatsapp-dispatch'

const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWaitlistRoute = AppWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPublicProfileRoute = AppPublicProfileRouteImport.update({
  id: '/public-profile',
  path: '/public-profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOperatorsRoute = AppOperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuRoute = AppMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AppRoute,
} as any)
const AppFloorPlanRoute = AppFloorPlanRouteImport.update({
  id: '/floor-plan',
  path: '/floor-plan',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCashierRoute = AppCashierRouteImport.update({
  id: '/cashier',
  path: '/cashier',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsRoute = AppBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicHooksWhatsappWebhookRoute =
  ApiPublicHooksWhatsappWebhookRouteImport.update({
    id: '/api/public/hooks/whatsapp-webhook',
    path: '/api/public/hooks/whatsapp-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWhatsappDispatchRoute =
  ApiPublicHooksWhatsappDispatchRouteImport.update({
    id: '/api/public/hooks/whatsapp-dispatch',
    path: '/api/public/hooks/whatsapp-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/book': typeof BookRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurants': typeof RestaurantsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/bookings': typeof AppBookingsRoute
  '/app/cashier': typeof AppCashierRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/floor-plan': typeof AppFloorPlanRoute
  '/app/menu': typeof AppMenuRoute
  '/app/operators': typeof AppOperatorsRoute
  '/app/public-profile': typeof AppPublicProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/waitlist': typeof AppWaitlistRoute
  '/r/$slug': typeof RSlugRoute
  '/app/': typeof AppIndexRoute
  '/api/public/hooks/whatsapp-dispatch': typeof ApiPublicHooksWhatsappDispatchRoute
  '/api/public/hooks/whatsapp-webhook': typeof ApiPublicHooksWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurants': typeof RestaurantsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/bookings': typeof AppBookingsRoute
  '/app/cashier': typeof AppCashierRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/floor-plan': typeof AppFloorPlanRoute
  '/app/menu': typeof AppMenuRoute
  '/app/operators': typeof AppOperatorsRoute
  '/app/public-profile': typeof AppPublicProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/waitlist': typeof AppWaitlistRoute
  '/r/$slug': typeof RSlugRoute
  '/app': typeof AppIndexRoute
  '/api/public/hooks/whatsapp-dispatch': typeof ApiPublicHooksWhatsappDispatchRoute
  '/api/public/hooks/whatsapp-webhook': typeof ApiPublicHooksWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/book': typeof BookRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurants': typeof RestaurantsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/bookings': typeof AppBookingsRoute
  '/app/cashier': typeof AppCashierRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/floor-plan': typeof AppFloorPlanRoute
  '/app/menu': typeof AppMenuRoute
  '/app/operators': typeof AppOperatorsRoute
  '/app/public-profile': typeof AppPublicProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/waitlist': typeof AppWaitlistRoute
  '/r/$slug': typeof RSlugRoute
  '/app/': typeof AppIndexRoute
  '/api/public/hooks/whatsapp-dispatch': typeof ApiPublicHooksWhatsappDispatchRoute
  '/api/public/hooks/whatsapp-webhook': typeof ApiPublicHooksWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/book'
    | '/login'
    | '/reset-password'
    | '/restaurants'
    | '/app/admin'
    | '/app/analytics'
    | '/app/billing'
    | '/app/bookings'
    | '/app/cashier'
    | '/app/customers'
    | '/app/floor-plan'
    | '/app/menu'
    | '/app/operators'
    | '/app/public-profile'
    | '/app/settings'
    | '/app/waitlist'
    | '/r/$slug'
    | '/app/'
    | '/api/public/hooks/whatsapp-dispatch'
    | '/api/public/hooks/whatsapp-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/login'
    | '/reset-password'
    | '/restaurants'
    | '/app/admin'
    | '/app/analytics'
    | '/app/billing'
    | '/app/bookings'
    | '/app/cashier'
    | '/app/customers'
    | '/app/floor-plan'
    | '/app/menu'
    | '/app/operators'
    | '/app/public-profile'
    | '/app/settings'
    | '/app/waitlist'
    | '/r/$slug'
    | '/app'
    | '/api/public/hooks/whatsapp-dispatch'
    | '/api/public/hooks/whatsapp-webhook'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/book'
    | '/login'
    | '/reset-password'
    | '/restaurants'
    | '/app/admin'
    | '/app/analytics'
    | '/app/billing'
    | '/app/bookings'
    | '/app/cashier'
    | '/app/customers'
    | '/app/floor-plan'
    | '/app/menu'
    | '/app/operators'
    | '/app/public-profile'
    | '/app/settings'
    | '/app/waitlist'
    | '/r/$slug'
    | '/app/'
    | '/api/public/hooks/whatsapp-dispatch'
    | '/api/public/hooks/whatsapp-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  BookRoute: typeof BookRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RestaurantsRoute: typeof RestaurantsRoute
  RSlugRoute: typeof RSlugRoute
  ApiPublicHooksWhatsappDispatchRoute: typeof ApiPublicHooksWhatsappDispatchRoute
  ApiPublicHooksWhatsappWebhookRoute: typeof ApiPublicHooksWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/waitlist': {
      id: '/app/waitlist'
      path: '/waitlist'
      fullPath: '/app/waitlist'
      preLoaderRoute: typeof AppWaitlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/public-profile': {
      id: '/app/public-profile'
      path: '/public-profile'
      fullPath: '/app/public-profile'
      preLoaderRoute: typeof AppPublicProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/operators': {
      id: '/app/operators'
      path: '/operators'
      fullPath: '/app/operators'
      preLoaderRoute: typeof AppOperatorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/menu': {
      id: '/app/menu'
      path: '/menu'
      fullPath: '/app/menu'
      preLoaderRoute: typeof AppMenuRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/floor-plan': {
      id: '/app/floor-plan'
      path: '/floor-plan'
      fullPath: '/app/floor-plan'
      preLoaderRoute: typeof AppFloorPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers': {
      id: '/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cashier': {
      id: '/app/cashier'
      path: '/cashier'
      fullPath: '/app/cashier'
      preLoaderRoute: typeof AppCashierRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bookings': {
      id: '/app/bookings'
      path: '/bookings'
      fullPath: '/app/bookings'
      preLoaderRoute: typeof AppBookingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/hooks/whatsapp-webhook': {
      id: '/api/public/hooks/whatsapp-webhook'
      path: '/api/public/hooks/whatsapp-webhook'
      fullPath: '/api/public/hooks/whatsapp-webhook'
      preLoaderRoute: typeof ApiPublicHooksWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/whatsapp-dispatch': {
      id: '/api/public/hooks/whatsapp-dispatch'
      path: '/api/public/hooks/whatsapp-dispatch'
      fullPath: '/api/public/hooks/whatsapp-dispatch'
      preLoaderRoute: typeof ApiPublicHooksWhatsappDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBillingRoute: typeof AppBillingRoute
  AppBookingsRoute: typeof AppBookingsRoute
  AppCashierRoute: typeof AppCashierRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppFloorPlanRoute: typeof AppFloorPlanRoute
  AppMenuRoute: typeof AppMenuRoute
  AppOperatorsRoute: typeof AppOperatorsRoute
  AppPublicProfileRoute: typeof AppPublicProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWaitlistRoute: typeof AppWaitlistRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBillingRoute: AppBillingRoute,
  AppBookingsRoute: AppBookingsRoute,
  AppCashierRoute: AppCashierRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppFloorPlanRoute: AppFloorPlanRoute,
  AppMenuRoute: AppMenuRoute,
  AppOperatorsRoute: AppOperatorsRoute,
  AppPublicProfileRoute: AppPublicProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWaitlistRoute: AppWaitlistRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  BookRoute: BookRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RestaurantsRoute: RestaurantsRoute,
  RSlugRoute: RSlugRoute,
  ApiPublicHooksWhatsappDispatchRoute: ApiPublicHooksWhatsappDispatchRoute,
  ApiPublicHooksWhatsappWebhookRoute: ApiPublicHooksWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
